[package]
name = "xpanda"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
criterion = { version = "0.4.0", features = ["html_reports"] }

[dependencies]

[[bench]]
name = "bench"
path = "benches/bench.rs"
harness = false
